# Generated by Django 4.2.4 on 2024-12-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("level1", "0002_alter_recipe_time_of_preparing_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.CharField(default=3654376, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="Time_of_preparing",
            field=models.IntegerField(),
        ),
    ]
